import { _electron as electron } from 'playwright';
import { createRequire } from 'node:module';
import * as fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { randomUUID } from 'node:crypto';
const require=createRequire(import.meta.url);
const root=await fs.mkdtemp(path.join(os.tmpdir(),'workfoli-desktop-test-'));
const source=path.join(root,'source');await fs.mkdir(path.join(source,'_memoria'),{recursive:true});await fs.mkdir(path.join(source,'site'));
await fs.writeFile(path.join(source,'_memoria','empresa.md'),'Nome: Estúdio Horizonte\nPúblico-alvo: Pequenas empresas\n');
await fs.writeFile(path.join(source,'brand-guide.md'),'Cor principal: #425D43\n## Tipografia\nSite: Lora (títulos) + Inter (corpo)\nRedes sociais: Sora (títulos) + Nunito (corpo)\n');
await fs.writeFile(path.join(source,'site','index.html'),'<html><script>throw Error("IMPORTED_CODE_MUST_NEVER_RUN")</script><h1>Site de teste</h1></html>');
await fs.writeFile(path.join(source,'.env'),'API_KEY=synthetic-secret-value');
await fs.writeFile(path.join(source,'workfoli.base.json'),JSON.stringify({format:'workfoli-base',schemaVersion:1,baseId:randomUUID(),company:{name:'Estúdio Horizonte'},profile:'agency',modules:['overview','files','knowledge','projects'],paths:{memory:'_memoria',identity:'identidade'}}));
await fs.mkdir('test-results',{recursive:true});
const env={...process.env,WORKFOLI_DATA_DIR:path.join(root,'data')};delete env.ELECTRON_RUN_AS_NODE;delete env.WORKFOLI_DEV_URL;
const launchArgs=[...(process.env.WORKFOLI_EXECUTABLE?[]:['.']),`--user-data-dir=${path.join(root,'browser-profile')}`];
let app;
try{
  app=await electron.launch({executablePath:process.env.WORKFOLI_EXECUTABLE||require('electron'),args:launchArgs,env,timeout:30000});
  const page=await app.firstWindow();
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.getByTestId('environment-company').waitFor({timeout:30000});
  await page.getByTestId('environment-company').fill('Agência Operadora');
  await page.getByTestId('environment-user').fill('Operador sintético');
  await page.screenshot({path:'test-results/00-identidade.png',fullPage:true});
  await page.getByTestId('save-environment').click();
  await page.getByRole('dialog',{name:'Primeiro, o seu contexto.'}).waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Todos os clientes',exact:true}).click();
  await page.getByTestId('first-client').waitFor({timeout:30000});
  await page.screenshot({path:'test-results/01-clientes.png',fullPage:true});
  assert.equal(await page.evaluate(()=>typeof window.require),'undefined');
  const security=await app.evaluate(({BrowserWindow})=>{const prefs=BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();return {sandbox:prefs.sandbox,nodeIntegration:prefs.nodeIntegration,contextIsolation:prefs.contextIsolation};});
  assert.deepEqual(security,{sandbox:true,nodeIntegration:false,contextIsolation:true});
  await app.evaluate(({dialog},sourcePath)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[sourcePath]});},source);
  await page.getByTestId('first-client').click();
  await page.getByTestId('select-folder').click();
  await page.getByTestId('client-name').waitFor({timeout:30000});
  await page.getByTestId('client-name').fill('Estúdio Horizonte');
  assert.equal(await page.getByTestId('confirm-import').isDisabled(),true);
  await page.getByTestId('relationship-client').check();
  await page.getByRole('navigation',{name:'Etapas de revisão'}).getByRole('button',{name:/Conhecimento/}).click();
  await page.locator('.knowledge-card').filter({has:page.getByRole('heading',{name:'Nome do cliente',exact:true})}).locator('.evidence-link').click();
  await page.locator('.evidence-highlight').waitFor();
  assert.ok((await page.locator('.evidence-highlight').textContent()).includes('Estúdio Horizonte'));
  await page.getByRole('button',{name:'Fechar prévia'}).click();
  await page.screenshot({path:'test-results/02-revisao.png',fullPage:true});
  await page.getByTestId('confirm-import').click();
  await page.getByRole('heading',{name:'Visão geral.',exact:true}).waitFor();
  await page.getByText('Base da empresa reconhecida',{exact:true}).waitFor();
  await page.screenshot({path:'test-results/03-workspace.png',fullPage:true});
  await page.getByRole('navigation',{name:'Áreas do cliente'}).getByRole('button',{name:'Arquivos',exact:true}).click();
  await page.getByRole('button',{name:'index.html',exact:true}).click();
  await page.locator('.text-preview').waitFor();
  assert.ok((await page.locator('.text-preview').textContent()).includes('<script>'));
  await page.getByRole('button',{name:'Fechar prévia'}).click();
  await page.getByRole('button',{name:'.env',exact:true}).click();
  await page.getByRole('heading',{name:'Prévia indisponível'}).waitFor();
  assert.ok(!(await page.locator('body').textContent()).includes('synthetic-secret-value'));
  await page.getByRole('button',{name:'Fechar prévia'}).click();
  await page.getByRole('navigation',{name:'Áreas do cliente'}).getByRole('button',{name:/Conhecimento/}).click();
  await page.locator('.knowledge-card').first().waitFor();
  const nameCard=page.locator('.knowledge-card').filter({has:page.getByRole('heading',{name:'Nome do cliente',exact:true})});
  await nameCard.getByRole('button',{name:'Confirmar',exact:true}).click();
  await nameCard.locator('.status-confirmed').waitFor();
  await nameCard.getByRole('button',{name:'Editar Nome do cliente',exact:true}).click();
  await nameCard.getByRole('textbox',{name:'Editar valor: Nome do cliente'}).fill('Estúdio Horizonte revisado');
  await nameCard.getByRole('button',{name:'Salvar alteração'}).click();
  await nameCard.getByText('Corrigido por você',{exact:true}).waitFor();
  await nameCard.locator('.status-confirmed').waitFor();
  await page.getByRole('textbox',{name:'Buscar conhecimento'}).fill('Nome do cliente');
  assert.equal(await page.locator('.knowledge-card').count(),1);
  await page.getByRole('textbox',{name:'Buscar conhecimento'}).fill('');
  await page.screenshot({path:'test-results/04-conhecimento.png',fullPage:true});
  // Simulate a 0.1 workspace in this synthetic, disposable data directory only.
  const catalog=new DatabaseSync(path.join(root,'data','catalog.sqlite'));
  const workspaceId=catalog.prepare('SELECT id FROM workspaces').get().id;
  const database=new DatabaseSync(path.join(root,'data','workspaces',workspaceId,'workspace.sqlite'));
  const files=database.prepare('SELECT data FROM files').all().map(row=>JSON.parse(row.data));
  const guide=files.find(file=>file.path.endsWith('brand-guide.md'));
  const incorrect={id:randomUUID(),field:'business.website',value:'Lora + Inter',category:'Empresa',origin:'explicit',status:'pending',evidence:{fileId:guide.id,path:guide.path,line:3}};
  database.prepare('INSERT INTO knowledge VALUES (?,?)').run(incorrect.id,JSON.stringify(incorrect));
  const color=database.prepare('SELECT id,data FROM knowledge').all().find(row=>JSON.parse(row.data).field==='brand.primaryColor');
  database.prepare('DELETE FROM knowledge WHERE id=?').run(color.id);
  database.close();catalog.close();
  await page.getByRole('button',{name:'Workfoli — início'}).click();
  await page.getByRole('heading',{name:'Estúdio Horizonte',exact:true}).click();
  await page.getByRole('navigation',{name:'Áreas do cliente'}).getByRole('button',{name:/Conhecimento/}).click();
  await page.getByTestId('reanalyze-knowledge').click();
  await page.getByTestId('apply-reanalysis').waitFor();
  await page.getByRole('button',{name:'Pendentes removidos',exact:true}).click();
  await page.getByRole('dialog',{name:'Reanalisar conhecimento',exact:true}).getByText('Lora + Inter',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Revisados preservados',exact:true}).click();
  await page.getByRole('dialog',{name:'Reanalisar conhecimento',exact:true}).getByText('Estúdio Horizonte revisado',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Proposta para revisão',exact:true}).click();
  await page.screenshot({path:'test-results/05-reanalise.png',fullPage:true});
  await page.getByTestId('apply-reanalysis').click();
  await page.getByRole('dialog',{name:'Reanalisar conhecimento',exact:true}).waitFor({state:'hidden'});
  await nameCard.getByText('Estúdio Horizonte revisado',{exact:true}).waitFor();
  assert.equal(await page.getByRole('heading',{name:'Site',exact:true}).count(),0);
  assert.ok((await fs.readdir(path.join(root,'data','workspaces',workspaceId,'backups'))).length===1);
  await page.getByTestId('reanalyze-knowledge').click();
  await page.getByText('O conhecimento já está atualizado com esta análise.').waitFor();
  assert.equal(await page.getByTestId('apply-reanalysis').isDisabled(),true);
  await page.getByRole('button',{name:'Fechar reanálise'}).click();
  // Identity and workspace relationships are local; revisions remain intact.
  await page.getByTestId('change-relationship').click();
  await page.getByTestId('confirm-relationship').click();
  await page.getByRole('dialog',{name:'Usar como minha empresa'}).waitFor({state:'hidden'});
  assert.equal(await page.evaluate(async()=> (await window.workfoli.getEnvironment()).company.name),'Estúdio Horizonte');
  await page.getByRole('button',{name:'Todos os clientes',exact:true}).click();
  await page.getByTestId('first-client').waitFor();
  await page.getByRole('button',{name:'Minha empresa',exact:true}).click();
  await page.getByRole('heading',{name:'Visão geral.',exact:true}).waitFor();
  await page.getByRole('button',{name:'Ver contexto',exact:true}).click();
  await page.getByRole('dialog',{name:'Contexto da minha empresa'}).getByText('Estúdio Horizonte revisado',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Fechar contexto'}).click();
  const packagePath=path.join(root,'entrega.workfoli.zip');
  await app.evaluate(({dialog},filePath)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath});},packagePath);
  await page.getByTestId('export-workspace').click();
  await page.getByTestId('confirm-export').click();
  await page.getByRole('dialog',{name:'Exportar Estúdio Horizonte'}).waitFor({state:'hidden'});
  assert.ok((await fs.stat(packagePath)).size>100);
  const backupPath=path.join(root,'full.workfoli-backup');
  await app.evaluate(({dialog},filePath)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath});},backupPath);
  await page.getByRole('button',{name:'Sobre o Workfoli'}).click();
  await page.getByTestId('open-backup').click();
  await page.getByTestId('backup-password').fill('synthetic-desktop-password');
  await page.getByTestId('backup-password-confirm').fill('synthetic-desktop-password');
  await page.getByTestId('create-backup').click();
  await page.getByRole('status').filter({hasText:'full.workfoli-backup'}).waitFor();
  await page.screenshot({path:'test-results/06-backup.png',fullPage:true});
  await page.getByRole('button',{name:'Fechar backup'}).click();
  assert.deepEqual(errors,[]);
  const after=await fs.readFile(path.join(source,'.env'),'utf8');assert.equal(after,'API_KEY=synthetic-secret-value');
  await app.close();app=undefined;
  // Reopen the same data directory to verify real persisted state.
  app=await electron.launch({executablePath:process.env.WORKFOLI_EXECUTABLE||require('electron'),args:launchArgs,env,timeout:30000});
  const reopened=await app.firstWindow();await reopened.getByRole('heading',{name:'Visão geral.',exact:true}).waitFor({timeout:30000});
  assert.equal(await reopened.getByTestId('environment-company').count(),0);
  assert.equal(await reopened.evaluate(async()=> (await window.workfoli.listWorkspaces()).filter(w=>w.relationship==='client').length),0);
  await app.close();app=undefined;
  // Recipient chooses to own the transferred company in a fresh environment.
  const recipientEnv={...env,WORKFOLI_DATA_DIR:path.join(root,'recipient')};
  app=await electron.launch({executablePath:process.env.WORKFOLI_EXECUTABLE||require('electron'),args:launchArgs,env:recipientEnv,timeout:30000});
  const recipient=await app.firstWindow();
  await recipient.getByTestId('environment-company').fill('Identificação inicial');
  await recipient.getByTestId('environment-user').fill('Pessoa destinatária');
  await recipient.getByTestId('save-environment').click();
  await recipient.getByTestId('import-company').click();
  await app.evaluate(({dialog},sourcePath)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[sourcePath]});},packagePath);
  await recipient.getByTestId('select-zip').click();
  await recipient.getByTestId('client-name').waitFor();
  assert.equal(await recipient.getByTestId('confirm-import').isDisabled(),true);
  await recipient.getByTestId('relationship-company').check();
  assert.equal(await recipient.getByTestId('client-name').inputValue(),'Estúdio Horizonte');
  await recipient.getByTestId('confirm-import').click();
  await recipient.getByRole('heading',{name:'Visão geral.',exact:true}).waitFor();
  const recipientState=await recipient.evaluate(async()=>{const profile=await window.workfoli.getEnvironment();const list=await window.workfoli.listWorkspaces();return {profile,list,data:await window.workfoli.getWorkspace(list[0].id)};});
  assert.equal(recipientState.profile.company.name,'Estúdio Horizonte');
  assert.equal(recipientState.profile.user.name,'Pessoa destinatária');
  assert.equal(recipientState.list.filter(w=>w.relationship==='client').length,0);
  assert.ok(recipientState.data.report.knowledge.some(k=>k.value==='Estúdio Horizonte revisado'&&k.status==='confirmed'));
  assert.ok(!recipientState.data.report.files.some(file=>file.path==='.env'));
  await recipient.screenshot({path:'test-results/07-entrega.png',fullPage:true});
  // Restore the full private backup into a new location through the native dialogs.
  const restoreRoot=path.join(root,'recovery');await fs.mkdir(restoreRoot);
  await app.evaluate(({dialog},{backupPath,restoreRoot})=>{let selection=0;dialog.showOpenDialog=async()=>({canceled:false,filePaths:[selection++===0?backupPath:restoreRoot]});},{backupPath,restoreRoot});
  await recipient.getByRole('button',{name:'Sobre o Workfoli'}).click();await recipient.getByTestId('open-backup').click();
  await recipient.getByRole('button',{name:'Recuperar ambiente',exact:true}).click();
  await recipient.getByTestId('backup-password').fill('synthetic-desktop-password');
  await recipient.getByTestId('restore-backup').click();
  await recipient.getByRole('dialog',{name:'Backup e recuperação'}).waitFor({state:'hidden'});
  await recipient.getByRole('heading',{name:'Visão geral.',exact:true}).waitFor();
  const recoveredState=await recipient.evaluate(async()=>{const profile=await window.workfoli.getEnvironment();const list=await window.workfoli.listWorkspaces();return {profile,data:await window.workfoli.getWorkspace(list[0].id),info:await window.workfoli.appInfo()};});
  assert.equal(recoveredState.profile.user.name,'Operador sintético');
  assert.equal(recoveredState.data.workspace.id,workspaceId);
  assert.ok(recoveredState.data.report.files.some(file=>file.path==='.env'&&file.sensitive));
  assert.ok(recoveredState.info.dataDirectory.startsWith(restoreRoot));
  console.log('PASS: desktop, identity, explicit relationships, safe import, editing, reanalysis, scoped context, neutral transfer, encrypted backup, isolated restore and restart.');
}catch(error){
  if(app){try{const page=await app.firstWindow();await page.screenshot({path:'test-results/failure.png',fullPage:true});console.error((await page.locator('body').textContent()).slice(0,3000));}catch{}}
  throw error;
}finally{
  if(app)await app.close();
  const relative=path.relative(os.tmpdir(),root);assert.ok(relative.startsWith('workfoli-desktop-test-')&&!relative.startsWith('..'));
  await fs.rm(root,{recursive:true,force:true,maxRetries:10,retryDelay:150});
}
